version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 5001:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hilite
    networks:
      - my-network

networks:
  my-network:
